spring.application.name=jwt-api
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true

server.error.include-stacktrace=never

api.security.token.secret=uma-chave-secreta-muito-maior-para-o-nosso-jwt-api-123456
api.security.token.expiration=86400000